micronaut:
  application:
    name: engine
  server:
    port: 1000
  config-client:
    enabled: true
  cors:
    enabled: true
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:public"

datasources:
  default:
    url: jdbc:postgresql://localhost:26257/cardsagainsthumanity
    driverClassName: org.postgresql.Driver
    username: 'dev'
    password: ''
    schema-generate: NONE
    dialect: POSTGRES
jpa:
  default:
    packages-to-scan:
      - 'com.cardsagainsthumanity'
    properties:
      hibernate:
      hbm2ddl:
        auto: update
      show_sql: true

consul:
  client:
    registration:
      enabled: true
      tags:
        - version=${version}
        - micronaut
      retry-count: 5
      fail-fast: false
      check:
        http: true
      meta:
        version: ${application.version:dev}
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"

flyway:
  datasources:
    default:
      enabled: true
      locations:
        - classpath:db/migration
        -
endpoints:
  flyway:
    enabled: true
    sensitive: false
  loggers:
    enabled: true
    sensitive: false

version: 1.2.3
rabbitmq:
  uri: amqp://localhost:5672