version: '3'

services:
  cockroachdb-0:
    image: cockroachdb/cockroach:v20.1.1
    command: start --insecure
    restart: on-failure
    volumes:
      - ./data/cockroachdb-0:/cockroach/cockroach-data
    ports:
      - "26257:26257"
      - "8080:8080"
    networks:
      - roachnet

  ######### Uncomment for 3 nodes
  #  cockroachdb-1:
  #    image: cockroachdb/cockroach:v20.1.1
  #    depends_on:
  #      - cockroachdb-0
  #    restart: on-failure
  #    command: start --insecure --join=cockroachdb-0
  #    volumes:
  #     - ./data/cockroachdb-1:/cockroach/cockroach-data
  #    networks:
  #      - roachnet
  #
  #  cockroachdb-2:
  #    image: cockroachdb/cockroach:v20.1.1
  #    depends_on:
  #      - cockroachdb-0
  #    restart: on-failure
  #    command: start --insecure --join=cockroachdb-0
  #    volumes:
  #     - ./data/cockroachdb-2:/cockroach/cockroach-data
  #    networks:
  #      - roachnet

  cardsagainsthumanity-init:
    image: cockroachdb/cockroach:v20.1.1
    depends_on:
      - cockroachdb-0
    restart: on-failure
    volumes:
      - ./:/home/
    entrypoint: /bin/bash
    command: /home/setup_db.sh
    networks:
      - roachnet

networks:
  roachnet: